---
# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: ftw
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - id: "ftw"
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    binary: ftw
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs"
      - "^test"
release:
  prerelease: auto
dockers:
  - image_templates:
      - "ghcr.io/coreruleset/go-ftw:{{ .Version }}-amd64"
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/coreruleset/go-ftw:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "ghcr.io/coreruleset/go-ftw:latest"
    image_templates:
      - "ghcr.io/coreruleset/go-ftw:{{ .Version }}-amd64"
      - "ghcr.io/coreruleset/go-ftw:{{ .Version }}-arm64"
  - name_template: "ghcr.io/coreruleset/go-ftw:{{ .Version }}"
    image_templates:
      - "ghcr.io/coreruleset/go-ftw:{{ .Version }}-amd64"
      - "ghcr.io/coreruleset/go-ftw:{{ .Version }}-arm64"
nfpms:
  - id: "ftw"
    builds: ["ftw"]
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    overrides:
      rpm:
        replacements:
          amd64: x86_64
        file_name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}"
      deb:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}_{{ .Arch }}"
    vendor:
    homepage: https://github.com/coreruleset/go-ftw
    maintainer: felipe.zipitria@owasp.org
    description: >
      Framework for Testing WAFs - Go version

      It uses the OWASP Core Ruleset V3 as a baseline to test rules on a WAF.
      Each rule from the ruleset is loaded into a YAML file that issues HTTP
      requests that will trigger these rules. Users can verify the execution
      of the rule after the tests are issued to make sure the expected
      response is received from an attack.
    license: APL2

announce:
  slack:
    enabled: true
    message_template: >
      "{{ .ProjectName }} {{ .Tag }} is out!
      Check it out at {{ .ReleaseURL }}"
    channel: "#coreruleset-notify"
    username: "Releaser"
    icon_emoji: ":new:"
    blocks:
      - type: section
        text:
          type: mrkdwn
          text: |
            "{{ .ReleaseNotes }}"
    attachments: []
